# Generated by Django 5.0 on 2023-12-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('current_setting', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=100)),
                ('status', models.CharField(choices=[('Inside', 'Inside'), ('Checked', 'Checked')], max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
