# Generated by Django 5.0 on 2023-12-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Super Deluxe', 'Super Deluxe'), ('Single', 'Single'), ('Double', 'Double')], max_length=50)),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper'), ('Two', 'Two'), ('All', 'All')], max_length=50)),
                ('bed_capacity', models.IntegerField()),
                ('air_condition', models.CharField(choices=[('AC', 'AC'), ('No AC', 'No AC')], max_length=50)),
                ('rent', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
