# Generated by Django 5.0 on 2023-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Super Deluxe', 'Super Deluxe'), ('Single', 'Single'), ('Double', 'Double')], max_length=50)),
                ('bed_capacity', models.CharField(choices=[('One', 'Two'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine')], max_length=50)),
                ('air_condition', models.CharField(choices=[('AC', 'AC'), ('No AC', 'No AC')], max_length=50)),
                ('rent', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Open', 'Open'), ('Inactive', 'Inactive')], default='Open', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
