# Generated by Django 5.0 on 2023-12-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='meal',
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_capacity',
            field=models.CharField(choices=[('One', 'Two'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine')], max_length=50),
        ),
    ]
