# Generated by Django 5.0 on 2023-12-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_remove_room_meal_alter_room_bed_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Open', 'Open'), ('Inactive', 'Inactive')], default='Open', max_length=50),
        ),
    ]
